// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gatewayapi/v1/message.proto

package gatewayapiv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MessageMultiError, or nil if none found.
func (m *Message) ValidateAll() error {
	return m.validate(true)
}

func (m *Message) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Cmd

	// no validation rules for Key

	// no validation rules for Body

	if len(errors) > 0 {
		return MessageMultiError(errors)
	}

	return nil
}

// MessageMultiError is an error wrapping multiple validation errors returned
// by Message.ValidateAll() if the designated constraints aren't met.
type MessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageMultiError) AllErrors() []error { return m }

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on OnReceiveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OnReceiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnReceiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnReceiveRequestMultiError, or nil if none found.
func (m *OnReceiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OnReceiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Body

	if len(errors) > 0 {
		return OnReceiveRequestMultiError(errors)
	}

	return nil
}

// OnReceiveRequestMultiError is an error wrapping multiple validation errors
// returned by OnReceiveRequest.ValidateAll() if the designated constraints
// aren't met.
type OnReceiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnReceiveRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnReceiveRequestMultiError) AllErrors() []error { return m }

// OnReceiveRequestValidationError is the validation error returned by
// OnReceiveRequest.Validate if the designated constraints aren't met.
type OnReceiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnReceiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnReceiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnReceiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnReceiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnReceiveRequestValidationError) ErrorName() string { return "OnReceiveRequestValidationError" }

// Error satisfies the builtin error interface
func (e OnReceiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnReceiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnReceiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnReceiveRequestValidationError{}

// Validate checks the field values on OnReceiveResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OnReceiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnReceiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnReceiveResponseMultiError, or nil if none found.
func (m *OnReceiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OnReceiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MsgId

	// no validation rules for BizId

	if len(errors) > 0 {
		return OnReceiveResponseMultiError(errors)
	}

	return nil
}

// OnReceiveResponseMultiError is an error wrapping multiple validation errors
// returned by OnReceiveResponse.ValidateAll() if the designated constraints
// aren't met.
type OnReceiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnReceiveResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnReceiveResponseMultiError) AllErrors() []error { return m }

// OnReceiveResponseValidationError is the validation error returned by
// OnReceiveResponse.Validate if the designated constraints aren't met.
type OnReceiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnReceiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnReceiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnReceiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnReceiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnReceiveResponseValidationError) ErrorName() string {
	return "OnReceiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OnReceiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnReceiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnReceiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnReceiveResponseValidationError{}

// Validate checks the field values on BatchOnReceiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchOnReceiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchOnReceiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchOnReceiveRequestMultiError, or nil if none found.
func (m *BatchOnReceiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchOnReceiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReqs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BatchOnReceiveRequestValidationError{
						field:  fmt.Sprintf("Reqs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BatchOnReceiveRequestValidationError{
						field:  fmt.Sprintf("Reqs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BatchOnReceiveRequestValidationError{
					field:  fmt.Sprintf("Reqs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BatchOnReceiveRequestMultiError(errors)
	}

	return nil
}

// BatchOnReceiveRequestMultiError is an error wrapping multiple validation
// errors returned by BatchOnReceiveRequest.ValidateAll() if the designated
// constraints aren't met.
type BatchOnReceiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchOnReceiveRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchOnReceiveRequestMultiError) AllErrors() []error { return m }

// BatchOnReceiveRequestValidationError is the validation error returned by
// BatchOnReceiveRequest.Validate if the designated constraints aren't met.
type BatchOnReceiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchOnReceiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchOnReceiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchOnReceiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchOnReceiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchOnReceiveRequestValidationError) ErrorName() string {
	return "BatchOnReceiveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BatchOnReceiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchOnReceiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchOnReceiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchOnReceiveRequestValidationError{}

// Validate checks the field values on BatchOnReceiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchOnReceiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchOnReceiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchOnReceiveResponseMultiError, or nil if none found.
func (m *BatchOnReceiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchOnReceiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BatchOnReceiveResponseValidationError{
						field:  fmt.Sprintf("Res[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BatchOnReceiveResponseValidationError{
						field:  fmt.Sprintf("Res[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BatchOnReceiveResponseValidationError{
					field:  fmt.Sprintf("Res[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BatchOnReceiveResponseMultiError(errors)
	}

	return nil
}

// BatchOnReceiveResponseMultiError is an error wrapping multiple validation
// errors returned by BatchOnReceiveResponse.ValidateAll() if the designated
// constraints aren't met.
type BatchOnReceiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchOnReceiveResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchOnReceiveResponseMultiError) AllErrors() []error { return m }

// BatchOnReceiveResponseValidationError is the validation error returned by
// BatchOnReceiveResponse.Validate if the designated constraints aren't met.
type BatchOnReceiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchOnReceiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchOnReceiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchOnReceiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchOnReceiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchOnReceiveResponseValidationError) ErrorName() string {
	return "BatchOnReceiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BatchOnReceiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchOnReceiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchOnReceiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchOnReceiveResponseValidationError{}

// Validate checks the field values on PushMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushMessageMultiError, or
// nil if none found.
func (m *PushMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *PushMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for BizId

	// no validation rules for ReceiverId

	// no validation rules for Body

	if len(errors) > 0 {
		return PushMessageMultiError(errors)
	}

	return nil
}

// PushMessageMultiError is an error wrapping multiple validation errors
// returned by PushMessage.ValidateAll() if the designated constraints aren't met.
type PushMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushMessageMultiError) AllErrors() []error { return m }

// PushMessageValidationError is the validation error returned by
// PushMessage.Validate if the designated constraints aren't met.
type PushMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushMessageValidationError) ErrorName() string { return "PushMessageValidationError" }

// Error satisfies the builtin error interface
func (e PushMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushMessageValidationError{}

// Validate checks the field values on PushRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushRequestMultiError, or
// nil if none found.
func (m *PushRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PushRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMsg()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PushRequestValidationError{
					field:  "Msg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PushRequestValidationError{
					field:  "Msg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMsg()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PushRequestValidationError{
				field:  "Msg",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PushRequestMultiError(errors)
	}

	return nil
}

// PushRequestMultiError is an error wrapping multiple validation errors
// returned by PushRequest.ValidateAll() if the designated constraints aren't met.
type PushRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushRequestMultiError) AllErrors() []error { return m }

// PushRequestValidationError is the validation error returned by
// PushRequest.Validate if the designated constraints aren't met.
type PushRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushRequestValidationError) ErrorName() string { return "PushRequestValidationError" }

// Error satisfies the builtin error interface
func (e PushRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushRequestValidationError{}

// Validate checks the field values on PushResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushResponseMultiError, or
// nil if none found.
func (m *PushResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PushResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PushResponseMultiError(errors)
	}

	return nil
}

// PushResponseMultiError is an error wrapping multiple validation errors
// returned by PushResponse.ValidateAll() if the designated constraints aren't met.
type PushResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushResponseMultiError) AllErrors() []error { return m }

// PushResponseValidationError is the validation error returned by
// PushResponse.Validate if the designated constraints aren't met.
type PushResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushResponseValidationError) ErrorName() string { return "PushResponseValidationError" }

// Error satisfies the builtin error interface
func (e PushResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushResponseValidationError{}
